<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Area of codes

class Cars{
    
 public $module; 
 public $car;
 public $year;
 function GetOwner(){
     
     $owner=array("Ayman","Ahmed","Osamh");
     return $owner;
             
       
 }
 
  


 
 
 
    
    
    
    
}


